import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hold My Beer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-white ${inter.className}`}>
        <>
          <nav className="fixed top-[8px] left-[8px]">
            <Link className="p-2 text-xs rounded-2xl bg-emerald-800" href={"/"}>
              HomeJa
            </Link>
          </nav>
          {children}
        </>
      </body>
    </html>
  );
}
